/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadGrupo54.vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author xavie
 */
public class FomularioporMatria extends javax.swing.JInternalFrame {

    /**
     * Creates new form FomularioporMatria
     */
    public FomularioporMatria() {
        initComponents();
        imagen_gif_guardar();
    }

    public void imagen_gif_guardar() {
        ImageIcon buscando;
       buscando = new ImageIcon(getClass().getResource("/imagenes/buscando.gif"));
        Icon gif = new ImageIcon(buscando.getImage().getScaledInstance(40, 40, Image.SCALE_DEFAULT));
        jLbuscar.setIcon(gif);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbuscar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioestado = new javax.swing.JRadioButton();
        jBbuscar = new javax.swing.JButton();
        jBnuevo = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscando.png"))); // NOI18N
        getContentPane().add(jLbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 30, 30));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Año:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 40, 20));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Estado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jTextField1.setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 210, 20));

        jTextField2.setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 180, 20));

        jTextField3.setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 100, 20));

        jRadioestado.setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().add(jRadioestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jBbuscar.setBackground(new java.awt.Color(102, 102, 102));
        jBbuscar.setText("Buscar");
        getContentPane().add(jBbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jBnuevo.setBackground(new java.awt.Color(102, 102, 102));
        jBnuevo.setText("Nuevo ");
        getContentPane().add(jBnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jBeliminar.setBackground(new java.awt.Color(102, 102, 102));
        jBeliminar.setText("Eliminar");
        getContentPane().add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jBguardar.setBackground(new java.awt.Color(102, 102, 102));
        jBguardar.setText("Gurdar");
        getContentPane().add(jBguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        jBsalir.setBackground(new java.awt.Color(102, 102, 102));
        jBsalir.setText("Salir ");
        getContentPane().add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/55.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 420, 310));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FooterUlpVirtualM7.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLbuscar;
    private javax.swing.JRadioButton jRadioestado;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
