/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadGrupo54.vista;

import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidadGrupo54.accesoADatos.AlumnoData;
import universidadGrupo54.accesoADatos.InscripcionData;
import universidadGrupo54.accesoADatos.MateriaData;
import universidadGrupo54.entidades.Alumno;
import universidadGrupo54.entidades.Inscripcion;
import universidadGrupo54.entidades.Materia;

/**
 *
 * @author Otras
 */
public class FormularioDeInscripcionesView extends javax.swing.JInternalFrame {

    private List<Materia> listaM;
    private List<Alumno> listaA;

    private InscripcionData inscData;
    private MateriaData matData;
    private AlumnoData aluData;

    private DefaultTableModel modelo;

    /**
     * Creates new form FormularioDeInscripcion
     */
    public FormularioDeInscripcionesView() {
        initComponents();

        aluData = new AlumnoData();
        listaA = aluData.listarAlumnos();
        modelo = new DefaultTableModel();
        inscData = new InscripcionData();
        matData = new MateriaData();

        cargaAlumnos();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRBmatInscriptas = new javax.swing.JRadioButton();
        jRBNoIncriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMateria = new javax.swing.JTable();
        jBinscribir = new javax.swing.JButton();
        jBanularInscripcion = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        CBoxAlumno = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(610, 620));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Formulario de Inscripcion");
        jLabel1.setFocusCycleRoot(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Seleccione un Alumno:");
        jLabel2.setFocusCycleRoot(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Listado de Materias");
        jLabel3.setFocusCycleRoot(true);

        jRBmatInscriptas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRBmatInscriptas.setForeground(new java.awt.Color(0, 51, 102));
        jRBmatInscriptas.setText("Materias Inscriptas");
        jRBmatInscriptas.setFocusCycleRoot(true);
        jRBmatInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBmatInscriptasActionPerformed(evt);
            }
        });

        jRBNoIncriptas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRBNoIncriptas.setForeground(new java.awt.Color(0, 51, 102));
        jRBNoIncriptas.setText("Materias NO Inscriptas");
        jRBNoIncriptas.setFocusCycleRoot(true);
        jRBNoIncriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNoIncriptasActionPerformed(evt);
            }
        });

        jTMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTMateria);

        jBinscribir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBinscribir.setForeground(new java.awt.Color(0, 51, 102));
        jBinscribir.setText("INSCRIBIR");
        jBinscribir.setEnabled(false);
        jBinscribir.setFocusCycleRoot(true);
        jBinscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinscribirActionPerformed(evt);
            }
        });

        jBanularInscripcion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBanularInscripcion.setForeground(new java.awt.Color(0, 51, 102));
        jBanularInscripcion.setText("ANULAR INSCRIPCION");
        jBanularInscripcion.setEnabled(false);
        jBanularInscripcion.setFocusCycleRoot(true);
        jBanularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBanularInscripcionActionPerformed(evt);
            }
        });

        jBSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBSalir.setForeground(new java.awt.Color(0, 51, 102));
        jBSalir.setText("SALIR");
        jBSalir.setFocusCycleRoot(true);
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        CBoxAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addComponent(CBoxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jRBmatInscriptas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRBNoIncriptas))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jBinscribir)
                                .addGap(44, 44, 44)
                                .addComponent(jBanularInscripcion)
                                .addGap(55, 55, 55)
                                .addComponent(jBSalir)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(CBoxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBmatInscriptas)
                            .addComponent(jRBNoIncriptas))
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(227, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBinscribir)
                            .addComponent(jBanularInscripcion)
                            .addComponent(jBSalir))
                        .addGap(122, 122, 122))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBmatInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBmatInscriptasActionPerformed
        // TODO add your handling code here:
        borrarFilasTabla();
        jRBNoIncriptas.setSelected(false);
        cargarDatosMateriasInscriptas();
        jBanularInscripcion.setEnabled(true);
        jBinscribir.setEnabled(false);
        
    }//GEN-LAST:event_jRBmatInscriptasActionPerformed

    private void CBoxAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxAlumnoActionPerformed

    private void jRBNoIncriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNoIncriptasActionPerformed
        // TODO add your handling code here:
        borrarFilasTabla();
        jRBmatInscriptas.setSelected(false);
        cargarDatosNoInscriptas();
        jBanularInscripcion.setEnabled(false);
        jBinscribir.setEnabled(true);
    }//GEN-LAST:event_jRBNoIncriptasActionPerformed

    private void jBinscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinscribirActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada=jTMateria.getSelectedRow();
        if(filaSeleccionada!=-1){
            Alumno a= (Alumno) CBoxAlumno.getSelectedItem();
            int idMateria=(Integer)modelo.getValueAt(filaSeleccionada, 0);
            String nombre=(String)modelo.getValueAt(filaSeleccionada, 1);
            int anioMateria=(Integer)modelo.getValueAt(filaSeleccionada, 2);
            Materia m=new Materia(idMateria, nombre, anioMateria, true);
            
            Inscripcion i=new Inscripcion(a,m,0);
            inscData.guardarInscripcion(i);
            borrarFilasTabla();
    }
    }//GEN-LAST:event_jBinscribirActionPerformed

    private void jBanularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBanularInscripcionActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada=jTMateria.getSelectedRow();
        if(filaSeleccionada!=-1){
            Alumno a=(Alumno)CBoxAlumno.getSelectedItem();
             int idMateria=(Integer)modelo.getValueAt(filaSeleccionada, 0);
             
             inscData.borrarInscripcionMateriaAlumno(a.getIdAlumno(), idMateria);
             borrarFilasTabla();   
        }else{
        JOptionPane.showMessageDialog(this, "Debe seleccionar una fila de la tabla. ");
        }
    }//GEN-LAST:event_jBanularInscripcionActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void cargaAlumnos() {//carga alumnos al combo box
        for (Alumno item : listaA) {
            CBoxAlumno.addItem(item);
        }
    }

    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID");
        filaCabecera.add("Nombre");
        filaCabecera.add("Año");
        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        jTMateria.setModel(modelo);

    }

    private void borrarFilasTabla() {
        int indice = modelo.getRowCount() - 1;

        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    private void cargarDatosNoInscriptas() {
//borrarFilasTabla();
        Alumno selec = (Alumno) CBoxAlumno.getSelectedItem();
        listaM= inscData.obtenerMateriasNOCursadas(selec.getIdAlumno());
        for(Materia matData: listaM){
                modelo.addRow(new Object[] { matData.getIdMateria(), matData.getNombre(), matData.getAnioMateria()});

        }
    }
    
    private void cargarDatosMateriasInscriptas(){
    //borrarFilasTabla();
    Alumno selec = (Alumno) CBoxAlumno.getSelectedItem();
    List <Materia> lista = (ArrayList) inscData.obtenerMateriasCursadas(selec.getIdAlumno());
    for(Materia matData: lista){
            modelo.addRow(new Object[] { matData.getIdMateria(), matData.getNombre(), matData.getAnioMateria()});
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> CBoxAlumno;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBanularInscripcion;
    private javax.swing.JButton jBinscribir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRBNoIncriptas;
    private javax.swing.JRadioButton jRBmatInscriptas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTMateria;
    // End of variables declaration//GEN-END:variables
}
