/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadGrupo54.vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import sun.net.www.content.image.gif;

/**
 *
 * @author xavie
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        imagen_gif_guardar();
        imagen2_gif_guardar();
        imagen3_gif_guardar();
        
        imagen5_gif_guardar();
    }

    public void imagen_gif_guardar() {
        ImageIcon birrete;
        birrete = new ImageIcon(getClass().getResource("/imagenes/birrete.gif"));
        Icon gif = new ImageIcon(birrete.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        jMalumno.setIcon(gif);

    }

    public void imagen2_gif_guardar() {
        ImageIcon libros;
        libros = new ImageIcon(getClass().getResource("/imagenes/libros.gif"));
        Icon gif = new ImageIcon(libros.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        jMmateria.setIcon(gif);
    }

    public void imagen3_gif_guardar() {
        ImageIcon universidad;
        universidad = new ImageIcon(getClass().getResource("/imagenes/universidad.gif"));
        Icon gif = new ImageIcon(universidad.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        jMadministracion.setIcon(gif);
    }
        public void imagen4_gif_guardar() {
            ImageIcon computadora;
            computadora = new  ImageIcon(getClass().getResource("/imagenes/computadora.gif"));
            Icon gif = new ImageIcon(computadora.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
            jMconsulta.setIcon(gif);
            
        
        }
  
    

    public void imagen5_gif_guardar() {
        ImageIcon salida;
        salida = new ImageIcon(getClass().getResource("/imagenes/salida.gif"));
        Icon gif = new ImageIcon(salida.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        jMsalir.setIcon(gif);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMalumno = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMmateria = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMadministracion = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMconsulta = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMsalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FooterUlpVirtualM7.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 580, 230));

        jMalumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/birrete.gif"))); // NOI18N
        jMalumno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMalumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMalumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenuItem2.setText("Formulario de Alumno");
        jMalumno.add(jMenuItem2);

        jMenuBar2.add(jMalumno);

        jMmateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libros.gif"))); // NOI18N
        jMmateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMmateria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenuItem3.setText("Formulario de Materia");
        jMmateria.add(jMenuItem3);

        jMenuBar2.add(jMmateria);

        jMadministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/universidad.gif"))); // NOI18N
        jMadministracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMadministracion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenuItem4.setText("Manejo de Inscripcion");
        jMadministracion.add(jMenuItem4);

        jMenuItem5.setText("Manipulacion de Notas");
        jMadministracion.add(jMenuItem5);

        jMenuBar2.add(jMadministracion);

        jMconsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/computadora.gif"))); // NOI18N
        jMconsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMconsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenuItem6.setText("Alumno por Materia");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMconsulta.add(jMenuItem6);

        jMenuBar2.add(jMconsulta);

        jMsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.gif"))); // NOI18N
        jMsalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuBar2.add(jMsalir);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMadministracion;
    private javax.swing.JMenu jMalumno;
    private javax.swing.JMenu jMconsulta;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu jMmateria;
    private javax.swing.JMenu jMsalir;
    // End of variables declaration//GEN-END:variables
}
